- name: Install Apache
  hosts: all
  become: true
  tasks:
    - name: Update repo index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache2 package and php support
      apt: 
        name: 
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache2 and php support for centOS
      dnf:
        name: 
          - https
          - php
        state: latest
      when: ansible_distribution == "CentOS"
